USER_NAME_SQL=your_username
PASSWORD_SQL=your_password
URL_SQL=your_database_url
BOT_TOKEN=your_telegram_bot_token
BOT_USERNAME=your_bot_username
proxy.host=your_proxy_host
proxy.port=your_proxy_port
telegram.allowed.chatId=your_chat_id